### ISSUE TITLE
Can't delete Food

### ISSUE THREAD

**Issue by NakedJavaScript** [NakedJavaScript/mensa-projekt#15]
![unbenannt](https://user-images.githubusercontent.com/13101659/35006051-cbe6e9d4-faf5-11e7-9fd7-27d22c92437f.PNG)

@Orangenspannung @WeZyBugFix You guys get this error too?

**Comment by WeZyBugFix** [comment]
**INFO:**
Food, that is already in a Tagesangebot and Food that is liked can't be deleted, because it's used as a Foreign key.
Fixed the Tagesangebot thing with an error message.

This could be a Solution for fixing the Like issue:
```
$checkTagesangebot= "SELECT * FROM mensa.tagesangebot WHERE speise_ID=$speiseID";
             if($checkTagesangebot->num_rows > 0) {
                     $conn->query(DELETE * FROM mensa.likes WHERE speise_ID = $speiseID`);
              }
                else {
                            //put out error message
                }
```
