### ISSUE TITLE
Success and error messages are above Modals

### ISSUE THREAD

**Issue by NakedJavaScript** [NakedJavaScript/mensa-projekt#17]
![bug1](https://user-images.githubusercontent.com/13101659/35194811-c9cce190-feb9-11e7-9304-ca7fdb14f05f.png)

Giving the modal an higher z-index will probably fix this issue

**Comment by WeZyBugFix** [comment]
Fixed in  **#16 "Delete old Records"** (just change z-index of alerts below the z-index of an modal. The defualt z-index of an modal is **1040**)
